### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by rootuser** [creativetimofficial/ct-soft-ui-dashboard-pro-tall#1]
Hello,

alas the installation does not work as described. I followed the 'get started' section in https://www.creative-tim.com/learning-lab/tailwind/html/installation-instructions/soft-ui-dashboard/

# Expected Behavior

Installation should simply work and product should be usable afterwards.

# Current Behavior

Installation gives no errors, but afterwards the app does not work. 

# Failure Information (for bugs)

I get a database QueryException:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fcc-gui.sessions' doesn't exist
select * from `sessions` where `id` = mNYriBKLy7kfSvy4TbKmJ5kKK0lMs61dMBa7RYKF limit 1

I DID execute the 'php artisan migrate --seed' command and it worked without errors. But indeed no table sessions was created; the output of the command is:

Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (14.64ms)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (13.83ms)
Migrating: 2019_08_19_000000_create_failed_jobs_table
Migrated:  2019_08_19_000000_create_failed_jobs_table (14.23ms)
Migrating: 2019_12_14_000001_create_personal_access_tokens_table
Migrated:  2019_12_14_000001_create_personal_access_tokens_table (20.63ms)
Migrating: 2022_07_14_100115_create_roles_table
Migrated:  2022_07_14_100115_create_roles_table (13.76ms)
Migrating: 2022_07_14_100126_create_tags_table
Migrated:  2022_07_14_100126_create_tags_table (14.06ms)
Migrating: 2022_07_14_100133_create_categories_table
Migrated:  2022_07_14_100133_create_categories_table (13.54ms)
Migrating: 2022_07_14_100350_create_items_table
Migrated:  2022_07_14_100350_create_items_table (13.98ms)
Migrating: 2022_07_14_100357_create_item_tag_table
Migrated:  2022_07_14_100357_create_item_tag_table (59.98ms)

(droping the seeding output messages here)

## Steps to Reproduce

Just follow the installatino steps and run 'php artisan serve' afterwards

## Context

* Device: PC
* Operating System: Windows 10 x64
* Browser and Version: Firefox 108.0.2

Kind regards,
Tom

**Comment by teamupdivision** [comment]
Hello 

Thank you for using Creative TIM! 

Sorry for the late response . Could you please send us the .env file? 

Thank you.
